version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - load-cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
      - install-deps:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save-cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
          paths:
            - "venv"
      - run:
          command: flake8 sebs --config=flake8.cfg --black-config=black.toml --tee --output-file flake-reports
          name: Python code lint with flake8
      - store_artifacts:
          path: flake-reports
          destination: flake-reports

workflows:
  main:
    jobs:
      - build-and-test

