version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            mypy_boto3
          name: Install pip dependencies
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            flake8 sebs --config=flake8.cfg --black-config=black.toml --tee --output-file flake-reports
          name: Python code lint with flake8
      - run:
          command: |
            . venv/bin/activate
            mypy sebs
          name: Python static code verification with mypy
      - store_artifacts:
          path: flake-reports
          destination: flake-reports
  test-aws:
    executor: python/default
    steps:
      - checkout
      - setup_remote_docker
          docker_layer_caching: true
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
          name: Install pip dependencies
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            tests/test_runner.py --deployment aws
          name: Execute AWS tests

workflows:
  main:
    jobs:
      - build
      - test-aws

